name: hbb-build

on: 
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mf6:
    name: build MODFLOW 6 in the container
    runs-on: ubuntu-latest
    container: jdhughes99/gaia-hbb:latest # Specify the Docker image
    steps:
      - name: Run a command inside the container
        run: echo "Hello from inside the container!"

      - name: get modflow6 repo
        run: |
          git clone https://github.com/MODFLOW-ORG/modflow6.git modflow6
        #   curl -L -o mf6.zip https://github.com/MODFLOW-ORG/modflow6/archive/refs/heads/develop.zip
        #   unzip mf6.zip

      - name: what's in the /usr/bin/ dir
        run: |
          ls -lh /usr/bin/

      - name: what's in the /opt/rh/devtoolset-10 dir
        run: |
          ls -lh /opt/rh/devtoolset-10

      - name: what's there
        run: |
          ls -lh
          source /opt/rh/devtoolset-10/enable

          which gcc
          which gfortran

          gcc --version
          gfortran  --version

      - name: build modflow6
        run: |
          source /opt/rh/devtoolset-10/enable

          export CC="/usr/bin/gcc"
          export FC="/usr/bin/gfortran"
          cd modflow6/make
          make clean
          make 

      - name: save modflow6
        run: |
          cd modflow6/bin
          ls -lh
