name: hbb-build

on: 
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docker:
    name: Build docker container with gfortran
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for advanced build features

      - name: Log in to Docker Hub (or other registry)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use GitHub Secret for username
          password: ${{ secrets.DOCKER_PASSWORD }} # Use GitHub Secret for password

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (current directory)
          push: true # Push the image to the registry
          tags: jdhughes99/gaia-hbb:latest # Image 


  build:
    name: build MODFLOW 6 in the container
    needs:
      - build_docker
    runs-on: ubuntu-latest
    container: phusion/holy-build-box-64:latest # Specify the Docker image
    steps:
      - name: Run a command inside the container
        run: echo "Hello from inside the container!"

      - name: Install additional dependencies
        run: |
          yum install -y git

      - name: get modflow6 repo
        run: |
          curl -L -o mf6.zip https://github.com/MODFLOW-ORG/modflow6/archive/refs/heads/develop.zip
          unzip mf6.zip

      - name: what's there
        run: |
          ls -lh
          which gcc
          which gfortran

      - name: build modflow6
        run: |
          cd modflow6-develop/make
          make clean
          make 

      - name: save modflow6
        run: |
          cd modflow6-develop/bin
          ls -lh
