name: hbb-build

on: 
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: phusion/holy-build-box-64:latest # Specify the Docker image
    steps:
      - name: Run a command inside the container
        run: echo "Hello from inside the container!"

      - name: get modflow6 repo
        run: |
          curl mf6.zip https://github.com/MODFLOW-ORG/modflow6/archive/refs/heads/develop.zip
          ls -lh

      - name: build modflow6
        run: |
          cd modflow6/make
          make

    